In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import arrow

In [3]:
df = pd.read_csv('./data/adzuna_extract.csv')

In [128]:
df.head()

,id,PostURL,Title,TitleKeyword,Tags,Description,PublicationDate,Location,Latitude,Longitude
0,1549335342,https://www.adzuna.com/land/ad/1549335342?se=Y...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,... for good. <strong>Data</strong> <strong>E...,2020-05-19T22:16:25Z,"['US', 'Illinois', 'Cook County', 'Chicago', '...",41.868494,-87.673975
1,1540746038,https://www.adzuna.com/land/ad/1540746038?se=Y...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-09T09:44:30Z,"['US', 'Washington', 'King County', 'Seattle']",47.608492,-122.336407
2,1537091904,https://www.adzuna.com/land/ad/1537091904?se=Y...,<strong>Data</strong> <strong>Engineer</strong...,<strong>Data</strong> <strong>Engineer</strong...,it-jobs,"Menlo Park, CA <strong>Data</strong> <strong>E...",2020-05-05T14:31:29Z,"['US', 'California', 'San Mateo County', 'Menl...",37.448491,-122.180281
3,1533100037,https://www.adzuna.com/land/ad/1533100037?se=Y...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,Role <strong>Data</strong> <strong>Engineer</s...,2020-04-30T17:27:52Z,"['US', 'Delaware', 'New Castle County', 'Wilmi...",39.731260,-75.545138
4,1550148404,https://www.adzuna.com/land/ad/1550148404?se=Y...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,Role FullStack <strong>Data</strong> <strong>E...,2020-05-20T15:30:36Z,"['US', 'New York']",42.522869,-75.574677

In [130]:
def keyword(text):
    """
    Formats keywords by 
    -lowercasing all letters 
    -replacing ' ' with '_'
    -replacing '-' with '_'
    """
    text = text.lower()
    text = text.replace(' ', '_')
    text = text.replace('-', '_')
    return text

In [131]:
def remove_html(text):
    """
    Removes HTML
    """
    return BeautifulSoup(text).get_text()

In [132]:
def format_date(text):
    """
    Formats Date to 'YYYY-MM-DD'
    """
    time = arrow.get(text)
    time = time.format('YYYY-MM-DD')
    return time

In [133]:
def adzuna_id(text):
    """
    Formats ADZUNA API IDs to A + original ID
    """
    return "A" + str(text)

In [135]:
df.head()

,id,PostURL,Title,TitleKeyword,Tags,Description,PublicationDate,Location,Latitude,Longitude
0,A1549335342,https://www.adzuna.com/land/ad/1549335342?se=Y...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,... for good. <strong>Data</strong> <strong>E...,2020-05-19T22:16:25Z,"['US', 'Illinois', 'Cook County', 'Chicago', '...",41.868494,-87.673975
1,A1540746038,https://www.adzuna.com/land/ad/1540746038?se=Y...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-09T09:44:30Z,"['US', 'Washington', 'King County', 'Seattle']",47.608492,-122.336407
2,A1537091904,https://www.adzuna.com/land/ad/1537091904?se=Y...,<strong>Data</strong> <strong>Engineer</strong...,<strong>Data</strong> <strong>Engineer</strong...,it-jobs,"Menlo Park, CA <strong>Data</strong> <strong>E...",2020-05-05T14:31:29Z,"['US', 'California', 'San Mateo County', 'Menl...",37.448491,-122.180281
3,A1533100037,https://www.adzuna.com/land/ad/1533100037?se=Y...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,Role <strong>Data</strong> <strong>Engineer</s...,2020-04-30T17:27:52Z,"['US', 'Delaware', 'New Castle County', 'Wilmi...",39.731260,-75.545138
4,A1550148404,https://www.adzuna.com/land/ad/1550148404?se=Y...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,Role FullStack <strong>Data</strong> <strong>E...,2020-05-20T15:30:36Z,"['US', 'New York']",42.522869,-75.574677

In [137]:
def apply(column, function):
    """
    Applies function to column
    """
    df[column] = df[column].apply(function)

In [138]:
# InsertedDate 

df['InsertedDate'] = arrow.utcnow().format("YYYY-MM-DD")

In [139]:
# APPLY ADZUNA ID

apply('id', adzuna_id)

In [140]:
# APPLY REMOVE_HTML FUNCTION

apply('Title', remove_html)
apply('TitleKeyword', remove_html)

In [141]:
# APPLY KEYWORD FUNCTION

apply('TitleKeyword', keyword)
apply('Tags', keyword)

In [142]:
# APPLY DATE FUNCTION

apply('PublicationDate', format_date)

In [143]:
df.head()

,id,PostURL,Title,TitleKeyword,Tags,Description,PublicationDate,Location,Latitude,Longitude,InsertedDate
0,AA1549335342,https://www.adzuna.com/land/ad/1549335342?se=Y...,Data Engineer,data_engineer,it_jobs,... for good. <strong>Data</strong> <strong>E...,2020-05-19,"['US', 'Illinois', 'Cook County', 'Chicago', '...",41.868494,-87.673975,2020-05-23
1,AA1540746038,https://www.adzuna.com/land/ad/1540746038?se=Y...,Data Engineer,data_engineer,it_jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-09,"['US', 'Washington', 'King County', 'Seattle']",47.608492,-122.336407,2020-05-23
2,AA1537091904,https://www.adzuna.com/land/ad/1537091904?se=Y...,Data Engineer / Lead Data Engineer,data_engineer_/_lead_data_engineer,it_jobs,"Menlo Park, CA <strong>Data</strong> <strong>E...",2020-05-05,"['US', 'California', 'San Mateo County', 'Menl...",37.448491,-122.180281,2020-05-23
3,AA1533100037,https://www.adzuna.com/land/ad/1533100037?se=Y...,Data Engineer,data_engineer,it_jobs,Role <strong>Data</strong> <strong>Engineer</s...,2020-04-30,"['US', 'Delaware', 'New Castle County', 'Wilmi...",39.731260,-75.545138,2020-05-23
4,AA1550148404,https://www.adzuna.com/land/ad/1550148404?se=Y...,Data Engineer,data_engineer,it_jobs,Role FullStack <strong>Data</strong> <strong>E...,2020-05-20,"['US', 'New York']",42.522869,-75.574677,2020-05-23

In [144]:
df.to_csv('./data/adzuna_transform.csv', index=None)