In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import arrow

In [3]:
df = pd.read_csv('./data/adzuna_extract.csv')

In [4]:
df.head()

,id,post_url,title,title_keyword,tags,description,publication_date,location,latitude,longitude
0,1549335342,https://www.adzuna.com/land/ad/1549335342?se=T...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,... for good. <strong>Data</strong> <strong>E...,2020-05-19T22:16:25Z,"['US', 'Illinois', 'Cook County', 'Chicago', '...",41.868494,-87.673975
1,1537091904,https://www.adzuna.com/land/ad/1537091904?se=T...,<strong>Data</strong> <strong>Engineer</strong...,<strong>Data</strong> <strong>Engineer</strong...,it-jobs,"Menlo Park, CA <strong>Data</strong> <strong>E...",2020-05-05T14:31:29Z,"['US', 'California', 'San Mateo County', 'Menl...",37.448491,-122.180281
2,1540746038,https://www.adzuna.com/land/ad/1540746038?se=T...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-09T09:44:30Z,"['US', 'Washington', 'King County', 'Seattle']",47.608492,-122.336407
3,1533100037,https://www.adzuna.com/land/ad/1533100037?se=T...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,Role <strong>Data</strong> <strong>Engineer</s...,2020-04-30T17:27:52Z,"['US', 'Delaware', 'New Castle County', 'Wilmi...",39.731260,-75.545138
4,1550148404,https://www.adzuna.com/land/ad/1550148404?se=T...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,Role FullStack <strong>Data</strong> <strong>E...,2020-05-20T15:30:36Z,"['US', 'New York']",42.522869,-75.574677

In [5]:
def keyword(text):
    """
    Formats keywords by 
    -lowercasing all letters 
    -replacing ' ' with '_'
    -replacing '-' with '_'
    """
    text = text.lower()
    text = text.replace(' ', '_')
    text = text.replace('-', '_')
    return text

In [6]:
def remove_html(text):
    """
    Removes HTML
    """
    return BeautifulSoup(text).get_text()

In [7]:
def format_date(text):
    """
    Formats Date to 'YYYY-MM-DD'
    """
    time = arrow.get(text)
    time = time.format('YYYY-MM-DD')
    return time

In [8]:
def adzuna_id(text):
    """
    Formats ADZUNA API IDs to A + original ID
    """
    return "A" + str(text)

In [9]:
df.head()

,id,post_url,title,title_keyword,tags,description,publication_date,location,latitude,longitude
0,1549335342,https://www.adzuna.com/land/ad/1549335342?se=T...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,... for good. <strong>Data</strong> <strong>E...,2020-05-19T22:16:25Z,"['US', 'Illinois', 'Cook County', 'Chicago', '...",41.868494,-87.673975
1,1537091904,https://www.adzuna.com/land/ad/1537091904?se=T...,<strong>Data</strong> <strong>Engineer</strong...,<strong>Data</strong> <strong>Engineer</strong...,it-jobs,"Menlo Park, CA <strong>Data</strong> <strong>E...",2020-05-05T14:31:29Z,"['US', 'California', 'San Mateo County', 'Menl...",37.448491,-122.180281
2,1540746038,https://www.adzuna.com/land/ad/1540746038?se=T...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-09T09:44:30Z,"['US', 'Washington', 'King County', 'Seattle']",47.608492,-122.336407
3,1533100037,https://www.adzuna.com/land/ad/1533100037?se=T...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,Role <strong>Data</strong> <strong>Engineer</s...,2020-04-30T17:27:52Z,"['US', 'Delaware', 'New Castle County', 'Wilmi...",39.731260,-75.545138
4,1550148404,https://www.adzuna.com/land/ad/1550148404?se=T...,<strong>Data</strong> <strong>Engineer</strong>,<strong>Data</strong> <strong>Engineer</strong>,it-jobs,Role FullStack <strong>Data</strong> <strong>E...,2020-05-20T15:30:36Z,"['US', 'New York']",42.522869,-75.574677

In [13]:
df['city'] = df['location'][-1]

In [15]:
df['location'][0]

"['US', 'Illinois', 'Cook County', 'Chicago', 'Illinois Medical District']"

In [14]:
df.head()

,id,post_url,title,title_keyword,tags,description,publication_date,location,latitude,longitude,city
0,1549335342,https://www.adzuna.com/land/ad/1549335342?se=T...,Data Engineer,Data Engineer,it-jobs,... for good. <strong>Data</strong> <strong>E...,2020-05-19T22:16:25Z,"['US', 'Illinois', 'Cook County', 'Chicago', '...",41.868494,-87.673975,"['US', 'Virginia', 'Richmond County']"
1,1537091904,https://www.adzuna.com/land/ad/1537091904?se=T...,Data Engineer / Lead Data Engineer,Data Engineer / Lead Data Engineer,it-jobs,"Menlo Park, CA <strong>Data</strong> <strong>E...",2020-05-05T14:31:29Z,"['US', 'California', 'San Mateo County', 'Menl...",37.448491,-122.180281,"['US', 'Virginia', 'Richmond County']"
2,1540746038,https://www.adzuna.com/land/ad/1540746038?se=T...,Data Engineer,Data Engineer,it-jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-09T09:44:30Z,"['US', 'Washington', 'King County', 'Seattle']",47.608492,-122.336407,"['US', 'Virginia', 'Richmond County']"
3,1533100037,https://www.adzuna.com/land/ad/1533100037?se=T...,Data Engineer,Data Engineer,it-jobs,Role <strong>Data</strong> <strong>Engineer</s...,2020-04-30T17:27:52Z,"['US', 'Delaware', 'New Castle County', 'Wilmi...",39.731260,-75.545138,"['US', 'Virginia', 'Richmond County']"
4,1550148404,https://www.adzuna.com/land/ad/1550148404?se=T...,Data Engineer,Data Engineer,it-jobs,Role FullStack <strong>Data</strong> <strong>E...,2020-05-20T15:30:36Z,"['US', 'New York']",42.522869,-75.574677,"['US', 'Virginia', 'Richmond County']"

In [10]:
def apply(column, function):
    """
    Applies function to column
    """
    df[column] = df[column].apply(function)

In [11]:
# 
columns_to_remove_html=["title", "title_keyword"]

for col in columns_to_remove_html:
    df[col] = df[col].apply(remove_html)

In [10]:
# InsertedDate 

df['inserted_date'] = arrow.utcnow().format("YYYY-MM-DD")

In [11]:
# APPLY ADZUNA ID

apply('id', adzuna_id)

In [17]:
# APPLY REMOVE_HTML FUNCTION

apply('title', remove_html)
apply('title_keyword', remove_html)

In [18]:
df

,id,post_url,title,title_keyword,tags,description,publication_date,location,latitude,longitude
0,1549335342,https://www.adzuna.com/land/ad/1549335342?se=T...,Data Engineer,Data Engineer,it-jobs,... for good. <strong>Data</strong> <strong>E...,2020-05-19T22:16:25Z,"['US', 'Illinois', 'Cook County', 'Chicago', '...",41.868494,-87.673975
1,1537091904,https://www.adzuna.com/land/ad/1537091904?se=T...,Data Engineer / Lead Data Engineer,Data Engineer / Lead Data Engineer,it-jobs,"Menlo Park, CA <strong>Data</strong> <strong>E...",2020-05-05T14:31:29Z,"['US', 'California', 'San Mateo County', 'Menl...",37.448491,-122.180281
2,1540746038,https://www.adzuna.com/land/ad/1540746038?se=T...,Data Engineer,Data Engineer,it-jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-09T09:44:30Z,"['US', 'Washington', 'King County', 'Seattle']",47.608492,-122.336407
3,1533100037,https://www.adzuna.com/land/ad/1533100037?se=T...,Data Engineer,Data Engineer,it-jobs,Role <strong>Data</strong> <strong>Engineer</s...,2020-04-30T17:27:52Z,"['US', 'Delaware', 'New Castle County', 'Wilmi...",39.731260,-75.545138
4,1550148404,https://www.adzuna.com/land/ad/1550148404?se=T...,Data Engineer,Data Engineer,it-jobs,Role FullStack <strong>Data</strong> <strong>E...,2020-05-20T15:30:36Z,"['US', 'New York']",42.522869,-75.574677
5,1544935967,https://www.adzuna.com/land/ad/1544935967?se=T...,Data Engineer,Data Engineer,it-jobs,Important <strong>Data</strong> <strong>Engine...,2020-05-14T15:37:30Z,"['US', 'California', 'San Francisco']",37.798085,-122.466538
6,1550124138,https://www.adzuna.com/land/ad/1550124138?se=T...,Data Engineer,Data Engineer,it-jobs,"Hi, Please find the below requirements. You ca...",2020-05-20T15:16:35Z,"['US', 'Washington', 'King County', 'Redmond']",47.670119,-122.118237
7,1521288337,https://www.adzuna.com/land/ad/1521288337?se=T...,Data Engineer,Data Engineer,it-jobs,Description We are seeking a highly talented <...,2020-04-14T22:54:56Z,"['US', 'New Jersey', 'Essex County', 'Newark']",40.735075,-74.173906
8,1551130791,https://www.adzuna.com/land/ad/1551130791?se=T...,Data Engineer,Data Engineer,it-jobs,Job Title <strong>Data</strong> <strong>Engine...,2020-05-21T15:29:41Z,"['US', 'Oregon', 'Multnomah County', 'Portland']",45.505603,-122.688215
9,1544828627,https://www.adzuna.com/land/ad/1544828627?se=T...,Data Engineer,Data Engineer,it-jobs,Job Title <strong>Data</strong> <strong>Engine...,2020-05-14T12:27:59Z,"['US', 'Oregon', 'Multnomah County', 'Portland']",45.505603,-122.688215
10,1548134006,https://www.adzuna.com/land/ad/1548134006?se=T...,Data Engineer,Data Engineer,it-jobs,Top Skills Details 1) 4 years of <strong>data<...,2020-05-18T21:22:34Z,"['US', 'Texas', 'Austin County']",29.918447,-96.258873
11,1545056861,https://www.adzuna.com/land/ad/1545056861?se=T...,Data Engineer,Data Engineer,it-jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-14T18:23:33Z,"['US', 'Ohio', 'Hamilton County', 'Cincinnati']",39.103197,-84.506488
12,1548994415,https://www.adzuna.com/land/ad/1548994415?se=T...,Data Engineer,Data Engineer,it-jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-19T18:55:04Z,"['US', 'Arizona', 'Maricopa County', 'Phoenix']",33.450000,-112.070000
13,1539235040,https://www.adzuna.com/land/ad/1539235040?se=T...,Data Engineer,Data Engineer,it-jobs,No need to be in Houston or relocate Wersquore...,2020-05-07T14:45:16Z,"['US', 'Missouri', 'Texas County', 'Houston']",37.326159,-91.955988
14,1542069817,https://www.adzuna.com/land/ad/1542069817?se=T...,DATA ENGINEER,DATA ENGINEER,it-jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-11T14:52:59Z,"['US', 'Virginia', 'Fairfax County', 'Mc Lean']",38.970000,-77.230000
15,1552144521,https://www.adzuna.com/land/ad/1552144521?se=T...,Data Engineers,Data Engineers,it-jobs,... <strong>Data</strong> <strong>Engineer</s...,2020-05-22T18:23:59Z,"['US', 'Virginia', 'Richmond County']",37.959676,-76.711917
16,1552144340,https://www.adzuna.com/land/ad/1552144340?se=T...,Data Engineers,Data Engineers,it-jobs,Description - Title <strong>Data</strong> <str...,2020-05-22T18:23:27Z,"['US', 'Virginia', 'Richmond County']",37.959676,-76.711917
17,1533100709,https://www.adzuna.com/land/ad/1533100709?se=T...,Data Engineer,Data Engineer,it-jobs,U.S. Citizens and those authorized to work in ...,2020-04-30T17:28:22Z,"['US', 'Virginia', 'Fairfax County', 'Vienna']",38.893471,-77.220397
18,1459792638,https://www.adzuna.com/land/ad/1459792638?se=T...,Data Engineer,Data Engineer,it-jobs,Hi Professionals. We have an immediate opening...,2020-02-21T06:50:39Z,"['US', 'Virginia', 'Richmond County']",37.959676,-76.711917
19,1552144263,https://www.adzuna.com/land/ad/1552144263?se=T...,Data Engineer,Data Engineer,it-jobs,Need only GC s Only W2 Title <strong>Data</str...,2020-05-22T18:23:15Z,"['US', 'Virginia', 'Richmond County']",37.959676,-76.711917

In [13]:
# APPLY KEYWORD FUNCTION

apply('title_keyword', keyword)
apply('tags', keyword)

In [16]:
# APPLY DATE FUNCTION

apply('publication_date', format_date)

In [17]:
df.head()

,id,post_url,title,title_keyword,tags,description,publication_date,location,latitude,longitude,inserted_date
0,A1549335342,https://www.adzuna.com/land/ad/1549335342?se=T...,Data Engineer,data_engineer,it_jobs,... for good. <strong>Data</strong> <strong>E...,2020-05-19,"['US', 'Illinois', 'Cook County', 'Chicago', '...",41.868494,-87.673975,2020-05-23
1,A1537091904,https://www.adzuna.com/land/ad/1537091904?se=T...,Data Engineer / Lead Data Engineer,data_engineer_/_lead_data_engineer,it_jobs,"Menlo Park, CA <strong>Data</strong> <strong>E...",2020-05-05,"['US', 'California', 'San Mateo County', 'Menl...",37.448491,-122.180281,2020-05-23
2,A1540746038,https://www.adzuna.com/land/ad/1540746038?se=T...,Data Engineer,data_engineer,it_jobs,<strong>Data</strong> <strong>Engineer</strong...,2020-05-09,"['US', 'Washington', 'King County', 'Seattle']",47.608492,-122.336407,2020-05-23
3,A1533100037,https://www.adzuna.com/land/ad/1533100037?se=T...,Data Engineer,data_engineer,it_jobs,Role <strong>Data</strong> <strong>Engineer</s...,2020-04-30,"['US', 'Delaware', 'New Castle County', 'Wilmi...",39.731260,-75.545138,2020-05-23
4,A1550148404,https://www.adzuna.com/land/ad/1550148404?se=T...,Data Engineer,data_engineer,it_jobs,Role FullStack <strong>Data</strong> <strong>E...,2020-05-20,"['US', 'New York']",42.522869,-75.574677,2020-05-23

In [18]:
df.to_csv('./data/adzuna_transform.csv', index=None)